FROM php-app:7.3

LABEL maintainer='ksungcaya'

RUN apt-get update \
    && apt-get install php7.3-xdebug \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY xdebug.ini /etc/php/7.3/mods-available/

EXPOSE 80 443

ENTRYPOINT ["docker-entrypoint"]
