FROM ubuntu:16.04

MAINTAINER ksungcaya

RUN apt-get update \
    && apt-get install php5.6-xdebug \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY xdebug.ini /etc/php/5.6/mods-available/

EXPOSE 9000

CMD ["php-fpm5.6"]
